### ISSUE TITLE
Issue with Installing under Mac OS

### ISSUE THREAD

**Issue by kinowashere** [maritos/magento2-performance-fixes#2]
Hello,

So I've got a `"magento/product-community-edition": "2.4.1"` project where I installed your dependency as per the instructions, but I'm getting an Exception `Cannot apply patch performance fix #1 - vendor/magento/framework/Config/Data.php (vendor/maritos/magento2-performance-fixes/vendorPatch/magento/framework/Config/Data.patch)!`. After running `composer install -vvv` I get the error in the image.
![image](https://user-images.githubusercontent.com/47314086/127360930-f9e98994-a51d-44eb-94db-40fa82bda388.png)

This is happening only under Mac OS machines, 2 in my team to be precise. I'm personally running Big Sur. We've deviced a solution for this problem locally, so I'm linking it here in case you'd like to test it out. The format of the files seems to be working fine with both Mac OS and our Linux based infrastructure.

**Comment by alex-79** [comment]
The same thing happens on Debian/Magento 2.3.7

**Comment by maritos** [comment]
@alex-79 Thanks for message / deatials. I should have more time soon and I will check it and fix this error.

**Comment by munkhulzii** [comment]
I had this issue in Mac OS as well. For me it looks like that the 2 lines below are missing in patch files: 
after the line with index add 
--- a/Config/Data.php
+++ b/Config/Data.php
in Data.patch as example. 

It will look like 
diff --git a/Config/Data.php b/Config/Data.php
index 3ee2rd..8349152 111644
--- a/Config/Data.php
+++ b/Config/Data.php
@@ -98,12 +98,33 @@
...

After all patches updated like this the composer was able to execute those patches. 

Would be nice if it is in repo.

**Comment by munkhulzii** [comment]
Oh, There is a pull request for this issue. I did not see it :-)

**Comment by MagicLegend** [comment]
@maritos Any word on this issue? I keep running into it and having to manually patch the patch :smile:

**Comment by maritos** [comment]
Sorry mate! I gonna pick this up on the weekend. :eyes:

**Comment by maritos** [comment]
@MagicLegend Sorry for the delay :) I have checked and merged the PR https://github.com/maritos/magento2-performance-fixes/pull/3 which should solve the issue.

Let me know! :eyes:

**Comment by MagicLegend** [comment]
@maritos No worries mate! Thank you  so much for merging it :blush:

**Comment by manuel-tm** [comment]
@maritos Thanks for the merge! Can you close the issue though? 

I can't really close it since I am not able to test it anymore myself.

**Comment by maritos** [comment]
Issue closed/solved

Thanks guys for supporting! :) @kinowashere @MagicLegend @munkhulzii
